{% set version = "0.3.2" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 0b1c20bc49da7d77f287d2be2b16b33c4583022ed8c5780ece59d9237f2d342c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib
    - seaborn
    - pandas
    - geopandas
    - cartopy
    - descartes
    - contextily >=1.0rc2

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.ops
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'High-level geospatial plotting for Python'

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
