{% set version = "0.4.4" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: b1b1c438456c2b7da55d38a4d9a9f0768fcf524bf96182bd1aabe2c573016451

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cartopy
    - contextily >=1.0.0
    - geopandas
    - mapclassify >=2.1
    - matplotlib-base
    - pandas
    - seaborn-base

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.ops
    - geoplot.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: High-level geospatial plotting for Python

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
