{% set version = "0.5.1" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 9614b2caa193a42de943afa2fea953d0997b9daf25ab2949be0681361a122790

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cartopy
    - contextily >=1.0.0
    - geopandas >=0.9.0
    - mapclassify >=2.1
    - matplotlib-base
    - pandas
    - seaborn-base

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.ops
    - geoplot.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: High-level geospatial plotting for Python

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
