{% set version = "0.2.2" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 7bf9c948192d93e4b829037da492f49eb53a7e8e52392a2706763fe8409dee14

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy
    - gdal
    - geopandas
    - matplotlib
    - pandas
    - seaborn

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.quad
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'High-level geospatial plotting for Python'

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
