{% set version = "0.1.1" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 4ae4086f3ba80b8936c119a76ae0bcb12b0e99665f1ef227e6f2697034aac8ae

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cartopy
    - gdal 2.1.*
    - geopandas
    - matplotlib
    - pandas
    - seaborn

test:
  imports:
    - geoplot

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  summary: 'High-level geospatial plotting for Python.'
  license_family: MIT

extra:
  recipe-maintainers:
    - residentmario
