{% set version = "0.2.1" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 7c10354efcc7283890609b48d659ccd4ef39ab7db40060b374938497a74c7bde

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy
    - gdal 2.2.*
    - geopandas
    - matplotlib
    - pandas
    - seaborn

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.quad
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  summary: 'High-level geospatial plotting for Python.'
  license_family: MIT

extra:
  recipe-maintainers:
    - residentmario
