{% set version = "0.2.3" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 0b40d483e4b1b0c612fb3ca0d61e766d9cc75a15cf2d10dd74771fb6f8c8e99d

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy
    - gdal
    - geopandas
    - matplotlib
    - pandas
    - seaborn

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.quad
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'High-level geospatial plotting for Python'

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
