{% set version = "0.2.4" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 5e42912016c88d48e44fe0603e9f0250cb29a539fc3e99ac30b9dd41893217af

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy
    - gdal
    - geopandas
    - matplotlib
    - pandas
    - seaborn

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.quad
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'High-level geospatial plotting for Python'

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
