{% set version = "0.2.0" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: 1ff16c0b621d625e141ea78b842af592ec8e85d358f7bc8c7bb58a88e7a995de

build:
  number: 1
  noarch: python
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - cartopy
    - gdal 2.2.*
    - geopandas
    - matplotlib
    - pandas
    - seaborn

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.quad
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  summary: 'High-level geospatial plotting for Python.'
  license_family: MIT

extra:
  recipe-maintainers:
    - residentmario
