{% set name = "geoplot" %}
{% set version = "0.1.1" %}
{% set md5 = "6cfdef89c92e196a86a764d365e3ddea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  md5: 6cfdef89c92e196a86a764d365e3ddea

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win]
  # Windows install requires resolving: https://github.com/SciTools/cartopy/issues/805
  skip: True  # [win or py<35]
  # Backporting to older Python versions: https://github.com/ResidentMario/geoplot/issues/24

  number: 0

requirements:
  build:
    - python
    - setuptools
    - gdal >=2.1.4
  run:
    - python
    - matplotlib
    - seaborn
    - pandas
    - geopandas
    - cartopy

test:
  imports:
    - geoplot

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  summary: 'High-level geospatial plotting for Python.'
  license_family: MIT

extra:
  recipe-maintainers:
    - residentmario
