{% set version = "0.4.1" %}

package:
  name: geoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoplot/geoplot-{{ version }}.tar.gz
  sha256: eb073436c5a1cb7f97caa217cdb109e6cad4f3774e657757005e3f0f5a3183ca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - seaborn
    - pandas
    - geopandas
    - cartopy
    - descartes
    - mapclassify
    - contextily >=1.0rc2

test:
  imports:
    - geoplot
    - geoplot.crs
    - geoplot.ops
    - geoplot.utils

about:
  home: https://github.com/ResidentMario/geoplot
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: High-level geospatial plotting for Python

extra:
  recipe-maintainers:
    - residentmario
    - ocefpaf
