# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CeEAB5kRUVzXfJ7aCJR82P01BPO4fRbLuUqfZ/uV9Gu+1HDI5M9b+y0YsHzD+724gTbi36R4Po3EPrGXSIlR/IwU6d7aXb1DQRzOxTN3IpCGjZY2PRdMWoh2XjPls77nl1/YtmRlrEad2rTgz4vKC4oZd4e2syQ8I3d0XwgFjktNhlNpb0zQdJmNNL2gEcmnKx9x/vOU4o5BaXmwt9fCHH/DEmT3jVCOclGD8Nile2azyrKczsx02JowhURERpRGwD82Fz6Ua1OcBCN5ssjou8aiqe0WE1FsBL4wL5QxcuDD03xntut5c2v94XgPsNoo05zIclCzwkVBOp3g1UUXLpEFJMP6mOGHltJxutQ2smCvIWQ/zZ+7/b+rPZDK5LOCJHbIwHlfjicI4gvO24yjqAmG+mZN4KYP21c/7VmajyPvl16UBe1deYtntx5FlgNt/FZlHC3BJ1Kb5dYgnptkGVIoQtSJLmLt9C3dtjkLzhD5g6D4jnx2PnHjRLjdyd8q4jIO1MmsxcaWcht2TZT8l5+4CxWDNqexooAW2wdJE54oZ3IErhX/Cc0N/9oFBrUMlDipqmWCsutzqPQLVlwaSAtgum2jtV2JaKwLsGVrfa1QxHupc1y/DX28+XexOR9yVw7QeLF1lApAgaLX2duxsOkG27Oy5R7n4+IeVlJi94k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
