travis:
  secure:
    BINSTAR_TOKEN: jfr7TmBC56ePeCZUDoYN1iQV0F2ItOE7JHdxF7gHBGNzFlbHsh7IQdk2LBFLCLEjdJoq0sb4F/etNhOY97oJ3zEIlOa/9YHDZjU5ap17XrnvGfLdr5KTlDxH3yhOXzEkHkf55Meas7F2PEr1+ixrPrtN7qcMBt12OV4zcDrxVtsa2WBXDXZkebutFiqeXoCbLl+9KWDlIz8MFRr6fVkJKvikgXn2apS8q/a2hNIzKjyAyKh0v1uR9K4u5MdzF1TPevicqDLJEZnyXW3WvUpH9xK7Epn6/u3Ibi4SN/JzXu+wVYi0yUV50QypL9jnvt8DRQAHBFMA268jBUB/0VHydyKEE5yUvI+MrE4ucpwnerqTcdxdXoF/s+G8M/t7N8i+4HEeDplWWucjKpFP2szbykKFg4bDaxfhp9nnCdpEEpNRQYmlwsOOTF65FGQZIfVxBwS3aff0N3SlllIr4+UJdHgNl43gpiWgMqVEHbhcJ0fuCrIz9kdv5lGZX9YSiMoK9vTqGY5fNKz7KsZr8InUlFQ9x8U6SJLjfWfyzOqw7NmmiT6RH6JuGzGQCD0xFvONH4vrI6mVsqPvFMMJ2sZ6A6wZ1EYgKmhbX/86exjVE1Wk+xq9WPjHK+avJV1XI/wgz7GdRIwwLQp8vY+6xExbQbZ2OqgeztrN6Ct8NcDiFvE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
